some additional helper functions
atlab/commons pull request #41
Opened 2017-02-03 00:02 UTC by olakiril

2017-02-21 22:07 UTC, eywalker requested changes
Avoid use of built-in Matlab functions as variable names.

2017-02-21 22:07 UTC, eywalker commented on lib/+ne7/+mat/getParams.m
> +    char = zeros(1,length(vararginput));
Since both `char` and `struc` are built-in Matlab functions, would you mind changing them to something else?

2017-02-22 03:07 UTC, olakiril commented
Edited on my mobile so adding 2 was the easiest thing to do...

2017-02-22 15:26 UTC, dimitri-yatsenko approved these changes
I approve but suggest improvements.

2017-02-22 15:26 UTC, dimitri-yatsenko commented on lib/+ne7/+ip/imgaussian.m
> +if(~exist('siz','var')), siz=sigma*6; end
6 sigma is excessive.  2.5 sigma is usually more than enough.

2017-02-22 15:26 UTC, dimitri-yatsenko commented on lib/+ne7/+ip/imgaussian.m
> +    if(ndims(I)==1)
The conditional blocks below contain repeated blocks and can be replaced by a single for loop.

2017-02-22 15:26 UTC, dimitri-yatsenko commented on lib/+ne7/+ip/imgaussian.m
> +        if(size(I,3)<4) % Detect if 3D or color image
How do you know if it's a color image? If its 3rd dimension is 2 or 3?  A more reliable test or option should be used.

2017-02-22 15:26 UTC, dimitri-yatsenko commented on lib/+ne7/+ip/imgaussian.m
> +            for k=1:size(I,3)
this loop is unnecessary since imfilter already filters each slice in the 3rd dimension.

2017-02-22 15:49 UTC, dimitri-yatsenko commented on lib/+ne7/+mat/getParams.m
> +    for i = 1:length(vararginput)
c = cellfun(@ischar, vararginput)
s = cellfun(@isstract, vararginput)

2017-02-22 15:51 UTC, dimitri-yatsenko commented on lib/+ne7/+mat/getParams.m
> +            char(i+1)=0;
so if something is not preceded by a string, it is simply skipped with no error message?

2017-02-22 15:53 UTC, dimitri-yatsenko commented on lib/+ne7/+mat/getParams.m
> +    if ~sum(struc)==0
`sum(struc)~=0` or `sum(struc)>0`

2017-02-22 19:09 UTC, eywalker commented
I agree with @dimitri-yatsenko in that there are a number of things that can be improved, but I'm approving this now for us to edit in the future.

2017-02-22 19:09 UTC, eywalker approved these changes

2017-02-22 19:09 UTC, merged